#!/bin/bash
set -e
cd "$(dirname "${BASH_SOURCE[0]}")"

repeat () {
  while "$@"; do sleep 1; done
}

dev () {
  export DEBUG=true
  repeat clojure -Adev -m user
}

run () {
  repeat clojure -m biff.core
}

"$@"
