(ns com.biffweb.ring-test
  (:require [clojure.test :refer [deftest is testing]]
            [clojure.string :as str]
            [com.biffweb.ring :as biff.ring :refer [defpath defroute path]]
            [taoensso.nippy :as nippy]))

(defpath home "/")
(defpath subscriptions "/subscriptions/:id")
(defpath subscription-route ["/subscriptions/:id" {:name ::subscription}])

(defroute test-route "/test-route"
  :get (fn [_ctx] {:status 200 :body "hello"}))

(defroute path-fn-route (home)
  :get (fn [_ctx] {:status 200 :body "home"}))

(defroute hiccup-route "/hiccup"
  :get (fn [_ctx] [:div "hello"]))

(defroute hiccup-body-route "/hiccup-body"
  :get (fn [_ctx] {:body [:main [:h1 "hello"]]}))

(defroute fx-route "/fx-test"
  [:com.biffweb.ring-test/query {:q "data"}]
  :get (fn [_ctx result] {:body (str "got: " result)}))

(defroute no-fx-route "/no-fx"
  :get (fn [_ctx] {:status 200}))

(defroute autogenerated-route
  :post (fn [_ctx] {:status 204}))

(defroute parameterized-route "/articles/:id"
  :get (fn [_ctx] {:status 200}))

(defn- handler-for [modules]
  (let [system ((:biff.core/init (biff.ring/module)) (atom modules))]
    (:biff.ring/handler system)))

(defn- response-header [header value-fn]
  (fn [handler]
    (fn [ctx]
      (assoc-in (handler ctx) [:headers header] (value-fn ctx)))))

(defn- decode-npy [path]
  (some-> (second (str/split path #"\?npy=" 2))
          (#(.decode (java.util.Base64/getUrlDecoder) ^String %))
          nippy/fast-thaw))

(deftest defroute-creates-route-vector
  (let [[uri handler-map] test-route]
    (is (= "/test-route" uri))
    (is (fn? (:get handler-map)))
    (is (nil? (:post handler-map)))
    (is (= #{:name :get} (set (keys handler-map))))))

(deftest defroute-generates-uri-and-route-name
  (let [[uri handler-map] autogenerated-route]
    (is (= "/_biff/api/com.biffweb.ring-test/autogenerated-route" uri))
    (is (= ::autogenerated-route (:name handler-map)))
    (is (= 204 (:status ((:post handler-map) {:request-method :post}))))))

(deftest defroute-accepts-uri-expressions
  (is (= "/" (first path-fn-route)))
  (is (= "/articles/:id" (first parameterized-route))))

(deftest defpath-returns-readable-paths
  (let [id #uuid "1dfcc5ea-1268-4604-8ec7-0c9d66400715"]
    (is (= "/" (home)))
    (is (= "/subscriptions/HfzF6hJoRgSOxwydZkAHFQ"
           (subscriptions id)))
    (is (= "/subscriptions/42"
           (subscription-route 42)))
    (let [path (home {})]
      (is (str/starts-with? path "/?npy="))
      (is (= {} (decode-npy path))))
    (let [path (subscriptions 42 {:foo "bar"})]
      (is (str/starts-with? path "/subscriptions/42?npy="))
      (is (= {:foo "bar"} (decode-npy path))))
    (is (= ["/subscriptions/42" {:foo "bar"}]
           (binding [biff.ring/*testing* true]
             (subscriptions 42 {:foo "bar"}))))))

(deftest path-validates-its-input
  (is (thrown-with-msg? clojure.lang.ExceptionInfo
                        #"string or a reitit-style route vector"
                        (path :not-a-route)))
  (is (thrown-with-msg? clojure.lang.ExceptionInfo
                        #"Wrong number of args"
                        (path "/users/:id")))
  (is (thrown-with-msg? clojure.lang.ExceptionInfo
                        #"Wrong number of args"
                        (path "/users/:id" 1 {} :extra)))
  (is (thrown-with-msg? AssertionError
                        #"should be a map"
                        (path "/users/:id" 1 [:not-a-map]))))

(deftest path-renders-strings-and-route-vectors
  (let [route ["/teams/:team-id/members/:member-id" {:name ::member}]]
    (is (= "/" (path "/")))
    (is (= "/teams/7/members/9"
           (path route 7 9)))
    (let [rendered (path route 7 9 {:tab "info"})]
      (is (str/starts-with? rendered "/teams/7/members/9?npy="))
      (is (= {:tab "info"} (decode-npy rendered))))
    (is (= ["/teams/7/members/9" {:tab "info"}]
           (binding [biff.ring/*testing* true]
             (path route 7 9 {:tab "info"}))))))

(deftest defroute-handler-runs-machine
  (let [[_ handler-map] test-route
        handler         (:get handler-map)]
    (is (= {:status 200 :body "hello"}
           (handler {:request-method :get})))))

(deftest defroute-wraps-hiccup
  (let [[_ handler-map] hiccup-route
        handler         (:get handler-map)
        response        (handler {:request-method :get})]
    (is (= 200 (:status response)))
    (is (= "text/html; charset=utf-8"
           (get-in response [:headers "content-type"])))
    (is (re-find #"<div>hello</div>" (:body response)))))

(deftest defroute-renders-hiccup-body-maps
  (let [[_ handler-map] hiccup-body-route
        handler         (:get handler-map)
        response        (handler {:request-method :get})]
    (is (= 200 (:status response)))
    (is (= "text/html; charset=utf-8"
           (get-in response [:headers "content-type"])))
    (is (re-find #"<main>" (:body response)))))

(deftest defroute-with-initial-fx
  (let [[_ handler-map] fx-route
        handler         (:get handler-map)]
    (is (= {:body "got: query-result"}
           (handler {:request-method :get
                     :biff.fx/handlers
                     {:com.biffweb.ring-test/query (fn [_ _opts] "query-result")}})))))

(deftest defroute-without-fx-no-wrap-result
  (let [[_ handler-map] no-fx-route
        handler         (:get handler-map)]
    (is (= {:status 200}
           (handler {:request-method :get})))))

(deftest wrap-path-param-uuids-decodes-url-safe-base64-uuids
  (let [request {:path-params {"id"   "HfzF6hJoRgSOxwydZkAHFQ"
                               "slug" "hello"}}
        seen    (atom nil)
        handler (biff.ring/wrap-path-param-uuids
                 (fn [ctx]
                   (reset! seen (:path-params ctx))
                   {:status 200}))]
    (handler request)
    (is (= #uuid "1dfcc5ea-1268-4604-8ec7-0c9d66400715"
           (get @seen "id")))
    (is (= "hello"
           (get @seen "slug")))))

(deftest wrap-path-param-uuids-leaves-other-values-alone
  (let [handler (biff.ring/wrap-path-param-uuids identity)]
    (is (= {:path-params {:id "short" :number 42}}
           (handler {:path-params {:id "short" :number 42}})))
    (is (= {:uri "/"}
           (handler {:uri "/"})))))

(deftest wrap-nippy-params-merges-deserialized-maps-and-swallows-errors
  (let [map-npy    (.encodeToString
                    (.withoutPadding (java.util.Base64/getUrlEncoder))
                    (nippy/freeze {:foo "hi"}))
        vector-npy (.encodeToString
                    (.withoutPadding (java.util.Base64/getUrlEncoder))
                    (nippy/freeze [:not-a-map]))
        captured   (atom [])
        handler    (biff.ring/wrap-nippy-params
                    (fn [ctx]
                      (swap! captured conj (:params ctx))
                      {:status 200}))]
    (handler {:params {:npy map-npy}})
    (handler {:params {:npy "not-base64"}})
    (handler {:params {:npy vector-npy}})
    (is (= {:npy map-npy :foo "hi"}
           (first @captured)))
    (is (= {:npy "not-base64"}
           (second @captured)))
    (is (= 3 (count @captured)))
    (is (= {:npy vector-npy}
           (nth @captured 2)))))

(deftest module-uses-route-groups-and-custom-middleware
  (let [handler
        (handler-for
         [{:biff.ring/routes
           ["/hello" {:get  (fn [_]
                              {:status  200
                               :headers {}
                               :body    "site"})
                      :name ::hello}]
           :biff.ring/base-middleware
           [(response-header
             "x-route-name"
             #(str (get-in % [:reitit.core/match :data :name])))]
           :biff.ring/site-middleware
           [(response-header "x-middleware-layer" (constantly "site"))]}
          {:biff.ring/api-routes
           ["/api/ping" {:get (fn [_]
                                {:status  200
                                 :headers {}
                                 :body    "api"})}]
           :biff.ring/api-middleware
           [(response-header "x-middleware-layer" (constantly "api"))]}])]
    (testing "site routes get site middleware and base middleware sees route data"
      (let [response (handler {:request-method :get
                               :uri            "/hello"
                               :headers        {}})]
        (is (= 200 (:status response)))
        (is (= "site" (get-in response [:headers "x-middleware-layer"])))
        (is (= ":com.biffweb.ring-test/hello"
               (get-in response [:headers "x-route-name"])))))
    (testing "api routes get api middleware"
      (let [response (handler {:request-method :get
                               :uri            "/api/ping"
                               :headers        {}})]
        (is (= 200 (:status response)))
        (is (= "api" (get-in response [:headers "x-middleware-layer"])))))))

(deftest module-uses-biff-ring-on-error-for-default-handler
  (let [handler
        (handler-for
         [{:biff.ring/routes
           ["/hello" {:get (fn [_] {:status 200 :body "site"})}]}])
        response
        (handler {:request-method :get
                  :uri            "/missing"
                  :headers        {}
                  :biff.ring/on-error
                  (fn [{:keys [status]}]
                    {:status status
                     :body   (str "custom " status)})})]
    (is (= 404 (:status response)))
    (is (= "custom 404" (:body response)))))

(deftest module-rebuilds-handler-when-modules-change
  (let [modules-var (atom [{:biff.ring/routes
                            ["/first" {:get (fn [_] {:status 200})}]}])
        handler     (:biff.ring/handler
                     ((:biff.core/init (biff.ring/module)) modules-var))
        request     {:request-method :get :headers {}}]
    (is (= 200 (:status (handler (assoc request :uri "/first")))))
    (reset! modules-var
            [{:biff.ring/routes
              ["/second" {:get (fn [_] {:status 201})}]}])
    (is (= 404 (:status (handler (assoc request :uri "/first")))))
    (is (= 201 (:status (handler (assoc request :uri "/second")))))))

(deftest wrap-internal-error-delegates-to-error-handler
  (let [exception (ex-info "boom" {})
        response  ((biff.ring/wrap-internal-error
                    (fn [_] (throw exception)))
                   {:biff.ring/on-error
                    (fn [{:keys [status ex]}]
                      {:status status :body (ex-message ex)})})]
    (is (= {:status 500 :body "boom"} response))))

(deftest wrap-https-scheme-respects-secure-setting
  (let [handler (biff.ring/wrap-https-scheme :scheme)]
    (is (= :https (handler {:scheme :http})))
    (is (= :http (handler {:scheme :http :biff.ring/secure false})))
    (is (= :https (handler {:scheme :https})))))

(deftest handler-serves-static-resources-outside-reitit-routes
  (let [handler (handler-for [])]
    (testing "static assets are served even when no reitit route matches"
      (let [response (handler {:request-method :get
                               :uri            "/css/test.css"
                               :headers        {}})
            body     (let [body (:body response)]
                       (if (instance? java.io.File body)
                         (slurp body)
                         body))]
        (is (= 200 (:status response)))
        (is (= "text/css"
               (get-in response [:headers "Content-Type"])))
        (is (= "body { color: rebeccapurple; }\n" body))))))

(deftest site-routes-accept-secret-reader-values
  (let [handler
        (handler-for
         [{:biff.ring/routes
           ["/hello" {:get (fn [_] {:status 200 :body "site"})}]}])
        response
        (handler {:request-method          :get
                  :uri                     "/hello"
                  :headers                 {}
                  :biff.ring/cookie-secret (constantly "ldlF/I/l7DYn6ahOHjGEhg==")})]
    (is (= 200 (:status response)))
    (is (= "site" (:body response)))))

(deftest site-routes-accept-plain-cookie-secrets
  (let [handler  (handler-for
                  [{:biff.ring/routes
                    ["/hello" {:get (fn [_] {:status 200 :body "site"})}]}])
        response (handler {:request-method          :get
                           :uri                     "/hello"
                           :headers                 {}
                           :biff.ring/cookie-secret "ldlF/I/l7DYn6ahOHjGEhg=="})]
    (is (= 200 (:status response)))
    (is (= "site" (:body response)))))

(deftest module-provides-fallback-session-store
  (let [system ((:biff.core/init (biff.ring/module)) (atom []))]
    (is (some? (:biff.ring/fallback-session-store system)))))

(deftest wrap-anti-forgery-websockets-rejects-invalid-websocket-requests
  (let [handler (biff.ring/wrap-anti-forgery-websockets (constantly {:status 200}))]
    (testing "missing base URL rejects websocket requests"
      (is (= 403
             (:status
              (handler {:headers {"upgrade"    "websocket"
                                  "connection" "Upgrade"}})))))
    (testing "matching origin is allowed"
      (is (= 200
             (:status
              (handler {:biff.ring/base-url "https://example.com"
                        :headers            {"upgrade"    "websocket"
                                             "connection" "Upgrade"
                                             "origin"     "https://example.com"}})))))
    (testing "origin mismatch is rejected"
      (is (= 403
             (:status
              (handler {:biff.ring/base-url "https://example.com"
                        :headers            {"upgrade"    "websocket"
                                             "connection" "Upgrade"
                                             "origin"     "https://evil.example.com"}})))))))
