#!/bin/bash
# Managed by Biff.

# Don't edit files/parts of files with ^this^ message. It means that Biff might
# update the file (e.g. when new versions come out), which would overwrite your
# changes. If you want Biff to stop managing files for you, remove the call to
# biff.project/update-{% if spa %}s{% else %}m{% endif %}pa-files in your app's main namespace.

# === DEV ===

build-css-dev () {
  mkdir -p www-dev/css/
  npx tailwindcss build tailwind.css -o www-dev/css/main.css
}

init () {
  if [ -f package.json ]; then
    npm install
  else
    npm init -y
    {% if spa %}npm install --save react react-dom
    npm install --save-dev shadow-cljs tailwindcss onchange
    {% else %}npm install --save-dev tailwindcss onchange{% endif %}
  fi
  build-css-dev
  if ! which packer > /dev/null; then
    echo Before deploying, you must install Packer. See https://learn.hashicorp.com/tutorials/packer/getting-started-install.
  fi
  if ! which terraform > /dev/null; then
    echo 'Before deploying, you must install Terraform and run \`(cd infra; terraform init)\`. See https://learn.hashicorp.com/tutorials/terraform/install-cli.'
  else
    (cd infra; terraform init)
  fi
  echo
  echo Initialization complete.
}

dev () {
  npx onchange tailwind.css -- ./task build-css-dev &
  trap 'kill $(jobs -p) 2> /dev/null' EXIT
  BIFF_ENV=dev clj {% if spa %}-A:cljs {% endif %}"$@" -M -m $MAIN_NS
}


# === BUILD ===

current-image-id () {
  curl -X GET -H 'Content-Type: application/json' \
              -H "Authorization: Bearer $DIGITALOCEAN_API_KEY" \
              "https://api.digitalocean.com/v2/images?private=true" \
    | node -e "
    var stdin = process.stdin,
        inputChunks = [];
    stdin.resume();
    stdin.setEncoding('utf8');
    stdin.on('data', function (chunk) {
        inputChunks.push(chunk);
    });
    stdin.on('end', function () {
        var imageId = JSON.parse(inputChunks.join(''))
                          .images
                          .filter(x => x.name === 'biff-webserver')
                          .sort((x, y) => (x.created_at < y.created_at) ? 1 : -1)[0]
                          .id;
        console.log(imageId);
    });"
}

build-image () {
  cat > infra/provisioners/00-config << EOD
# Managed by Biff
export MAIN_NS="$MAIN_NS"
export AUTHORIZED_KEYS="$PUBLIC_KEY"
export HOST="$HOST"
export LETSENCRYPT_EMAIL="$LETSENCRYPT_EMAIL"
export GIT_URL="$GIT_URL"
EOD
  (cd infra; packer build webserver.json)
  sed -i "s/.*IMAGE_ID.*/export IMAGE_ID=\"$(current-image-id)\" # Managed by Biff/" config/task.env
}

build-css () {
  NODE_ENV=production npx tailwindcss build tailwind.css -o resources/www/css/main.css
}

{% if spa %}build-cljs () {
  npx shadow-cljs release $CLJS_APPS
  for app in $CLJS_APPS; do
    mkdir -p resources/www/cljs/$app
    cp {www-dev,resources/www}/cljs/$app/main.js
  done
}

{% endif %}build-assets () {
  build-css
{% if spa %}  build-cljs
{% endif %}}


# === DEPLOY ===

generate-deploy-key () {
  ssh-keygen -t rsa -b 4096 -f config/deploy-key
  echo
  echo If you\'re using Github, enter the contents of config/deploy-key.pub
  echo at https://github.com/your_username/your_repo/settings/keys
}

ensure-clean-commit () {
  if ! (git status | grep -q "nothing to commit"); then
    echo You have uncommitted files. You must commit and push before deploying.
    exit 1
  fi
}

tf () {
  ensure-clean-commit
  export TF_VAR_digitalocean_api_key="${DIGITALOCEAN_API_KEY}"
  export TF_VAR_deploy_key="${DEPLOY_KEY}"
  export TF_VAR_image_id="${IMAGE_ID}"
  export TF_VAR_ssh_key_fingerprint="$(ssh-keygen -l -E md5 -f config/ssh-public-key | awk '{ print $2 }' | sed 's/^MD5://')"
  (cd infra; terraform "$@")
}

deploy () {
  ensure-clean-commit
  echo Updating config...
  scp config/main.edn root@$HOST:/home/biff/config/main.edn
  echo Deploying app...
  ssh root@$HOST systemctl restart biff
  echo Watching logs. Hit Ctrl-C to exit.
  ssh root@$HOST journalctl -u biff -f
}


# === MONITOR ===

logs () {
  ssh root@$HOST journalctl -u biff -f -n 300
}

prod-connect () {
  ssh -NL 7800:localhost:7888 root@$HOST
}


# === OTHER ===

help () {
  cat <<EOD
DEVELOP

./task init

  Run this if you just created this project or if you just cloned this project
  on a new machine.

./task dev

  Starts your app locally. Also, changes to tailwind.css will be applied
  whenever you save the file.

BUILD

./task build-image

  *Note*: update the contents of config/ before running this command.

  Builds a VM image with Packer. Run this at least once before deploying.
  Use \`./task tf apply\` to deploy the new image.

./task build-assets

  Compiles your CSS {% if spa %}and ClojureScript {% endif %}for production. Run this before each
  deploy (unless you didn't change anything). For now, commit and push the
  output (I'll add CI support later).

DEPLOY

*Note*: update the contents of config/ before running these commands.

./task generate-deploy-key

  Generates an SSH private/public key pair which you can use to deploy your
  code from a private git repository. If you're deploying from a public repo,
  you can ignore this command.

./task tf [command]

  Runs \`terraform [command]\` with needed environment variables set. Use
  \`./task tf apply\` to deploy infrastructure changes. The first time you run
  this, it will also deploy your app. Use \`./task tf plan\` to do a dry run.

  If you've already created infrastructure before using Terraform, you may need
  to use \`./task tf import\`. See
  https://www.terraform.io/docs/import/usage.html. For example, if you've
  already imported the domain example.com into DigitalOcean, you'll need to run
  \`./task tf import digitalocean_domain.default example.com\` (see
  https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/domain#import).

./task deploy

  Restarts your app in production using the latest pushed commit. For the first
  deploy, use \`./task tf apply\`; for subsequent deploys, use this command.

MONITOR

./task logs

  Watches the production logs, starting with the last 300 lines. If you see
  "No journal files were found", you may need to reboot the server
  (\`ssh root@$HOST reboot\`). Don't ask me why that helps; I don't know.

./task prod-connect

  Starts an SSH tunnel. Connect nrepl to port 7800 to eval code in production.
  (Be careful).

---

Tip: put \`alias t=./task\` in your .bashrc file.

See https://findka.com/biff for more documentation. For additional help,
join #biff on Clojurians Slack (http://clojurians.net) or send me an email
(tmp.2020@jacobobryant.com).
EOD
}
