#!/usr/bin/env bash
set -e

source config.sh

cmd () {
  ssh root@$SERVER "$@"
}

trench () {
  cmd trench -p 7888 -e "$@"
}

install-tailwind () {
  # todo maybe just infer TAILWIND_ARCH?
  curl -LO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-$TAILWIND_ARCH
  chmod +x tailwindcss-$TAILWIND_ARCH
  mkdir -p bin
  mv tailwindcss-$TAILWIND_ARCH bin/tailwindcss
}

watch-css () {
  if ! [ -x bin/tailwindcss ]; then
    install-tailwind
  fi
  bin/tailwindcss -i tailwind.css -o target/resources/public/css/main.css --watch
}

run () {
  clj "$@" \
    -J-XX:-OmitStackTraceInFastThrow \
    -M -m $MAIN_NS --port 7888 --middleware '[cider.nrepl/cider-middleware]'
}

dev () {
  echo 7888 > .nrepl-port
  BIFF_ENV=dev run &
  # I'd do `watch-css &`, but for some reason I can't get watch-css to work in
  # the background.
  watch-css
}

clean () {
  rm -rf target
}

post-receive () {
  run -P
  sudo systemctl restart app
}

deploy () {
  chmod 600 config.*
  rsync -a config.* app@$SERVER:
  time git push $DEPLOY_TO $DEPLOY_FROM
}

soft-deploy () {
  chmod 600 config.*
  rsync -a --info=name1 --delete \
    config.* \
    tailwind.* \
    deps.edn \
    task \
    src \
    resources \
    app@$SERVER:
  trench '"('$SOFT_DEPLOY_FN' @com.biffweb/system)"'
}

refresh () {
  trench '"(com.biffweb/refresh)"'
}

restart () {
  cmd systemctl reset-failed app.service
  cmd systemctl restart app
}

auto-soft-deploy-write () {
  soft-deploy
  ignore_until=$(date +%s.%N)
  # TODO make this cross-platform
  inotifywait --quiet --recursive --monitor --format "%e %w%f" \
      --event modify --event move --event create --event delete \
      . | while read changed
  do
      if [ $(echo "$(date +%s.%N) > $ignore_until" | bc) -eq 1 ] ; then
          ignore_until=$(echo "$(date +%s.%N) + 0.25" | bc)
          ( sleep 0.25 ; soft-deploy ) &
      fi
  done
}

logs () {
  ssh root@$SERVER journalctl -u app -f -n ${1:-300}
}

prod-repl () {
  echo Connect to nrepl port 7888
  echo 7888 > .nrepl-port
  ssh -NL 7888:localhost:7888 root@$SERVER
}

prod-dev () {
  prod-repl &
  auto-soft-deploy &
  logs
  trap 'killall ssh' INT
}

"$@"
