#!/bin/bash
set -e
cd "$(dirname "${BASH_SOURCE[0]}")"

repeat () {
  while "$@"; do sleep 1; done
}

run () {
  repeat clojure -m biff.core
}

dev () {
  BIFF_ENV=dev run
}

docs () {
  (cd slate; bundle exec middleman build --clean)
  rsync -av --delete slate/build/ docs/
}

"$@"
