#!/usr/bin/env bash

dev () {
  clj -M:dev
}

format () {
  clj -M:format
}

jar () {
  echo You updated the version in pom.xml, right?
  clj -Spom
  clj -X:jar :jar target/biff.jar
}

jar:deploy () {
  clj -X:deploy
}

"$@"
