#!/usr/bin/env bash

slate-dev () {
  cd slate
  bundle exec middleman server
}

slate () {
  cd slate
  bundle exec middleman build --clean
}

codox () {
  rm -rf site/codox
  clj -X:codox
}

jar () {
  clj -X:jar :jar target/biff.jar
}

deploy () {
  clj -X:deploy
}

"$@"
