#!/usr/bin/env bash
# When you push to the server, this file be taken from the commit and executed.

set -e
set +x

# Build
echo Building...
./task build

# Release
dir="$HOME/releases/$(date "+%Y-%m-%d_%H-%M-%S")"
mkdir -p $dir
cp target/app.jar ~/config.env $dir
cat > $dir/run.sh << EOD
#!/usr/bin/env bash
cd $HOME
source $dir/config.env
java -jar $dir/app.jar
EOD
chmod +x $dir/run.sh
rm -f ~/releases/current
ln -s $dir ~/releases/current

# Run
sudo systemctl restart app

# Cleanup
for dir in $(ls | grep -v current | head -n -10); do
  rm -r $dir
done
