(ns com.biffweb.tasks.update
  (:refer-clojure :exclude [update])
  (:require [antq.api :as antq]
            [clojure.edn :as edn]
            [clojure.java.io :as io]
            [com.biffweb.tasks.impl.bin :as bin]
            [com.biffweb.tasks.util :as util]))

(def ^:private deps-file "deps.edn")
(def ^:private kondo-dir ".clj-kondo")
(def ^:private code-quality-workflow-path ".github/workflows/code-quality.yml")
(def ^:private valid-flags #{"--deps-only" "--files-only" "--cache-only"})

(def ^:private code-quality-workflow
  "# This file is autogenerated by biff-tasks update. Do not edit.
name: code quality

on:
  push:
  pull_request:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'
      - uses: DeLaGuardo/setup-clojure@13.2
        with:
          cli: latest
      - run: clojure -M:run update --cache-only
      - run: clojure -M:run test
      - run: clojure -M:run lint
      - run: clojure -M:run format
      - run: git diff --quiet --exit-code
")

(defn- deps-path []
  (.getPath (io/file (System/getProperty "user.dir") deps-file)))

(defn- current-deps-edn [path]
  (-> path slurp edn/read-string))

(defn- upgradeable-deps [{:keys [deps aliases]}]
  (->> (concat deps (mapcat :extra-deps (vals aliases)))
       (remove (fn [[_dep coord]] (contains? coord :local/root)))
       (into {})))

(defn- write-generated-file! [relative-path contents]
  (let [file (io/file (System/getProperty "user.dir") relative-path)]
    (io/make-parents file)
    (spit file contents)
    file))

(defn- ensure-kondo-dir! []
  (.mkdirs (io/file (System/getProperty "user.dir") kondo-dir)))

(defn- configured-clj-kondo-version []
  (when (io/resource "config.edn")
    (:biff.tasks/clj-kondo-version (util/read-config))))

(defn- refresh-kondo-cache! [copy-configs?]
  (ensure-kondo-dir!)
  (let [binary (bin/ensure-binary! :clj-kondo (configured-clj-kondo-version))]
    (apply util/shell
           (cond-> [binary "--parallel" "--dependencies"]
             copy-configs? (conj "--copy-configs")
             true          (conj "--lint" (System/getProperty "java.class.path"))))))

(defn- write-code-quality-workflow! []
  (write-generated-file! code-quality-workflow-path code-quality-workflow))

(defn- deps-only! []
  (let [path                             (deps-path)
        {:keys [mvn/repos] :as deps-edn} (current-deps-edn path)
        outdated                         (antq/outdated-deps (upgradeable-deps deps-edn)
                                                             {:file-path    path
                                                              :repositories repos
                                                              :no-changes   true})]
    (when (seq outdated)
      (antq/upgrade-deps! (mapv #(hash-map :file path :dependency %) outdated)))
    nil))

(defn- files-only! []
  (write-code-quality-workflow!)
  (refresh-kondo-cache! true)
  nil)

(defn- cache-only! []
  (refresh-kondo-cache! false)
  nil)

(defn- validate-flags! [args]
  (let [unknown (remove valid-flags args)
        flags   (set args)]
    (when (seq unknown)
      (throw (ex-info "Unknown update flags" {:args args :unknown unknown})))
    (when (= 2 (count flags))
      (throw (ex-info "Choose at most one update mode flag."
                      {:args args :flags flags})))
    flags))

(defn update
  "Updates project dependencies and/or generated files.

   --deps-only  updates deps.edn only
   --files-only refreshes generated files and copied clj-kondo config only
   --cache-only refreshes clj-kondo dependency cache without copying tracked config files
   no flags     does both, running files-only in a subprocess after deps update"
  [& args]
  (let [flags (validate-flags! args)]
    (cond
      (flags "--deps-only")
      (deps-only!)

      (flags "--files-only")
      (files-only!)

      (flags "--cache-only")
      (cache-only!)

      :else
      (do
        (deps-only!)
        (util/shell "clojure" "-M:run" "update" "--files-only")
        nil))))
