#!/usr/bin/env bash
set -e

if [ -f config/task.env ]; then
  source config/task.env
fi

init () {
  mkdir -p target/resources
  if ! [ -d node_modules ]; then
    if [ -f package.json ]; then
      npm install
    else
      npm init -y
      npm install --save react react-dom
      npm install --save-dev shadow-cljs
    fi
  fi
}

dev () {
  init
  source config/dev.env
  clj "$@" -A:dev -M -m example.dev --port 7888 \
    --middleware '[shadow.cljs.devtools.server.nrepl/middleware
                   cider.nrepl/cider-middleware]'
}

build () {
  rm -rf target
  init
  clj -A:dev -X {{parent-ns}}.dev/build
}

deploy () {
  scp config/prod.env app@$TASK_HOST:config.env
  time git push prod master
}

logs () {
  ssh root@$TASK_HOST journalctl -u app -f -n 300
}

prod-repl () {
  echo Connect to nrepl port 7888
  ssh -NL 7888:localhost:7888 root@$TASK_HOST
}

"$@"
