name: code quality

on:
  push:

jobs:
  code-quality:
    strategy:
      matrix:
        runner:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-15-intel
          - macos-15
          - windows-2025
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - uses: DeLaGuardo/setup-clojure@13.2
        with:
          cli: latest
      - run: clojure -M:run code-quality
      - run: git diff --quiet --exit-code
