name: code quality

on:
  push:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - uses: DeLaGuardo/setup-clojure@13.2
        with:
          cli: latest
      - run: clj -M:run code-quality
      - run: git diff --quiet --exit-code
