name: code quality

on:
  push:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'
      - uses: DeLaGuardo/setup-clojure@13.2
        with:
          cli: latest
      - run: bin/test-all
      - run: clojure -M:run update --cache-only
      - run: clojure -M:run lint
      - run: clojure -M:run format
      - run: git diff --quiet --exit-code
      - run: bin/docs
      - run: git diff --quiet --exit-code -- libs/*/docs/api
